---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>
  use_sudo: false
  disable_upstart: false
  # start upstart
  run_command: /sbin/init
  # privileged required, as zookeper upstart jobs tunes limits (nofile)
  privileged: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.6
    driver_config:
      image: centos:6.6
      platform: centos
  
suites:
  - name: ubuntu
    excludes:
      - centos-6.6
    run_list:
      - recipe[spacewalk-client::ubuntu]
    attributes:
      spacewalk:
        reg:
          key: "1-ubuntu12.04-key"
          server: "http://spacewalk.hc.lan"
  - name: centos
    excludes:
      - ubuntu-12.04
    run_list:
      - recipe[spacewalk-client::rhel]  
    attributes:
      spacewalk:
        reg:
          key: "1-centos6"
          server: "http://spacewalk.hc.lan"